apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-yamldeployment
spec:
  replicas: 5
  template: 
    metadata:
      labels:
        app: web_server
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
